### ISSUE TITLE
Crash Booting Server

### ISSUE THREAD

**Issue by XileForce** [TechReimagined/Tech-Reimagined#16]
Server Crashes saying tech reimagined threw an exception. tried both builds of the mod that are on curse and updated to latest forge.

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  LoadingPlugin (Quark-beta-24.jar)
  Reborn Core ASM (RebornCore-1.9.4-2.5.3.44-universal.jar)
  LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  IC2core (industrialcraft-2-2.5.17-ex19.jar)
  FMLPlugin (InventoryTweaks-1.61-dev-53.jar)
  TransformerLoader (OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar)
  EnderCorePlugin (EnderCore-1.9.4-0.4.0.24-alpha.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 6/12/16 8:47 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.InstantiationException
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:81)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:546)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:525)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:92)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:118)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:429)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.InstantiationException
	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:64)
	... 27 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_92, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1280953192 bytes (1221 MB) / 2077753344 bytes (1981 MB) up to 5298978816 bytes (5053 MB)
	JVM Flags: 17 total; -Xmx5G -Xms2G -XX:+UseTLAB -XX:+ParallelRefProcEnabled -XX:ConcGCThreads=8 -XX:+CMSParallelRemarkEnabled -XX:+CMSClassUnloadingEnabled -XX:+AlwaysPreTouch -XX:+UseGCTaskAffinity -XX:+BindGCTaskThreadsToCPUs -XX:ParallelGCThreads=8 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+UseFastAccessorMethods -XX:+AggressiveOpts
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.28 Powered by Forge 12.17.0.1960 79 mods loaded, 79 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (Forge.jar) 
	UC	Forge{12.17.0.1960} [Minecraft Forge] (Forge.jar) 
	UC	OpenComputers|Core{1.6.0.2-beta.3} [OpenComputers (Core)] (minecraft.jar) 
	UC	actuallyadditions{1.9.4-r44} [Actually Additions] (ActuallyAdditions-1.9.4-r44.jar) 
	UC	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UC	baublesstuff{2.0.10} [Baubles Stuff] (baublesstuff-2.0.10.jar) 
	UC	bdlib{1.11.0.1} [BD Lib] (bdlib-1.11.0.1-mc1.9.4.jar) 
	UC	BiomesOPlenty{4.1.0.2025} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2025-universal.jar) 
	UC	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.9.4-alpha-1.0.0a.jar) 
	UC	JEI{3.6.3.212} [Just Enough Items] (jei_1.9.4-3.6.3.212.jar) 
	UC	BloodMagic{1.9.4-2.0.1-43} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.1-43.jar) 
	UC	Botania{r1.8-308} [Botania] (Botania-unofficial.r1.8-308.jar) 
	UC	Chameleon{1.9-2.1.4} [Chameleon] (Chameleon-1.9-2.1.4.jar) 
	UC	chiselsandbits{10.5} [Chisels & Bits] (chiselsandbits-10.5.jar) 
	UC	gg5cookiemod{0.4} [Cookie Obsession Mod] (cookieObsession-0.4.jar) 
	UC	correlatedpotentialistics{1.1.2} [Correlated Potentialistics] (CorrelatedPotentialistics-1.1.2.jar) 
	UC	cyclopscore{0.6.3} [Cyclops Core] (CyclopsCore-1.9.4-0.6.3.jar) 
	UC	ElecCore{1.5.292} [ElecCore] (ElecCore-1.9.4-1.5.292.jar) 
	UC	deepresonance{1.1.4beta32} [DeepResonance] (deepresonance-1.9.4-1.1.4beta32.jar) 
	UC	ea{v2.3.4d-mc1.9.4} [Ebon Arts] (EbonArts-v2.3.4d-mc1.9.4.jar) 
	UC	endercore{1.9.4-0.4.0.24-alpha} [EnderCore] (EnderCore-1.9.4-0.4.0.24-alpha.jar) 
	UC	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UC	EnderIO{1.9.4-3.0.0.40_alpha} [Ender IO] (EnderIO-1.9.4-3.0.0.40_alpha.jar) 
	UC	enderrift{0.16.3} [Ender-Rift] (EnderRift-1.9.4-0.16.3.jar) 
	UC	EnderZoo{1.9.4-1.2.2.40} [Ender Zoo] (EnderZoo-1.9.4-1.2.2.40.jar) 
	UC	ValkyrieLib{1.9.4-0.9.9} [Valkyrie Lib] (valkyrielib-1.9.4-0.9.9.jar) 
	UC	EnvironmentalTech{1.9.4-0.9.3i} [Environmental Tech] (environmentaltech-1.9.4-0.9.3i.jar) 
	UC	evilcraft{0.10.2} [EvilCraft] (EvilCraft-1.9.4-0.10.2.jar) 
	UC	ExtraBitManipulation{1.9-2.1.2} [Extra Bit Manipulation] (ExtraBitManipulation-1.9.4-2.1.0.jar) 
	UC	IC2{2.5.17-ex19} [IndustrialCraft 2] (industrialcraft-2-2.5.17-ex19.jar) 
	UC	OpenComputers{1.6.0.2-beta.3} [OpenComputers] (OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar) 
	UC	FFS{1.9.4-1.6.0-b19} [Fancy Fluid Storage] (Fancy Fluid Storage-1.9.4-1.6.0-b19.jar) 
	UC	frt{6.2.1.17} [Fire's Random Things] (FiresRandomThings-6.2.1.17.jar) 
	UC	frtvc{3.2} [Fire's Random Things Version Checker] (FiresRandomThings-6.2.1.17.jar) 
	UC	IronChest{6.0.144.786} [Iron Chest] (ironchest-1.9.4-6.0.144.786.jar) 
	UC	randomthings{3.7.3} [Random Things] (RandomThings-MC1.9.4-3.7.3.jar) 
	UC	xreliquary{1.9.4-1.3.2.372} [Reliquary] (Reliquary-1.9.4-1.3.2.372.jar) 
	UC	fluidity{6.0.0.5} [Fluidity] (Fluidity-6.0.0.5.jar) 
	UC	fluxducts{1.0.4} [Flux Ducts] (fluxducts-mc1.9.4-1.0.4.jar) 
	UC	forestry{5.0.11.148} [Forestry] (forestry_1.9.4-5.0.11.148.jar) 
	UC	pressure{1.3.1.1} [Pressure Pipes] (pressure-1.3.1.1-mc1.9.4.jar) 
	UC	advgenerators{0.9.20.1} [Advanced Generators] (generators-0.9.20.1-mc1.9.4.jar) 
	UC	gravestone{1.3.0} [Gravestone] (Gravestone Mod 1.3.0.jar) 
	UC	HelpFixer{1.3.14} [HelpFixer] (HelpFixer-1.9.4-1.3.14.jar) 
	UC	InfernalMobs{1.7.0} [Infernal Mobs] (InfernalMobs-1.9.4.jar) 
	UC	integrateddynamics{0.3.10} [Integrated Dynamics] (IntegratedDynamics-1.9.4-0.3.10.jar) 
	UC	inventorytweaks{1.61-dev-53-0736dc3} [Inventory Tweaks] (InventoryTweaks-1.61-dev-53.jar) 
	UC	journeymap{1.9.4-5.2.1} [JourneyMap] (journeymap-1.9.4-5.2.1-fairplay.jar) 
	UC	jet_packs{1.0.0} [Just JetPacks] (JustJetpacks-1.9.4-1.0.0.jar) 
	UC	gg5lootmod{0.6} [Loot Mod] (LootMod-1.9.4-0.6.jar) 
	UC	LunatriusCore{1.1.2.35} [LunatriusCore] (LunatriusCore-1.9.4-1.1.2.35-universal.jar) 
	UC	mantle{1.9.4-0.10.1.jenkins142} [Mantle] (Mantle-1.9.4-0.10.1.jenkins142.jar) 
	UC	ModLister{1.9.4-2.1.5} [ModLister] (ModLister-1.9.4-2.1.5.jar) 
	UC	nethermetals{1.1.0} [Nether Metals] (NetherMetals_1.9-1.1.0.jar) 
	UC	fodc{1.8.2} [Ore Dictionary Converter] (OreDictionaryConverter-1.8.2.jar) 
	UC	harvestcraft{1.9.4-pre} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4a.jar) 
	UC	progressiveautomation{1.6.46} [Progressive Automation] (ProgressiveAutomation-1.9.4-1.6.46.jar) 
	UC	Psi{beta-33} [Psi] (Psi-beta-33.jar) 
	UC	quantumflux{2.0.7} [QuantumFlux] (quantumflux-1.9.4-2.0.7.jar) 
	UC	Quark{beta-24} [Quark] (Quark-beta-24.jar) 
	UC	reborncore{2.5.3.44} [RebornCore] (RebornCore-1.9.4-2.5.3.44-universal.jar) 
	UC	reborncore-mcmultipart{2.5.3.44} [reborncore-MCMultiPart] (RebornCore-1.9.4-2.5.3.44-universal.jar) 
	UC	Reconstructor{2.6} [Reconstructor] (Reconstructor-2.6.jar) 
	UC	rftools{4.51} [RFTools] (rftools-1.9.4-4.51.jar) 
	UC	Roguelike{1.5.2} [Roguelike Dungeons] (RoguelikeDungeons-1.9.4-1.5.2.jar) 
	UC	solarvillage{1.0.0.7} [Solar Village] (SolarVillage-1.9.4-1.0.0.11.jar) 
	UC	soulshardstow{1.9.4-2.4.0-28} [Soul Shards - The Old Ways] (SoulShards-TOW-1.9.4-2.4.0-28.jar) 
	UC	Stackie{1.6.0.42} [Stackie] (Stackie-1.9.4-1.6.0.42-universal.jar) 
	UC	StorageDrawers{1.9-3.1.7} [Storage Drawers] (StorageDrawers-1.9-3.1.7.jar) 
	UC	tconstruct{1.9.4-2.3.1.jenkins229} [Tinkers' Construct] (TConstruct-1.9.4-2.3.1.jenkins229.jar) 
	UC	techreborn{1.3.2.120} [TechReborn] (TechReborn-1.9.4-1.3.2.120-universal.jar) 
	UE	techreimagined{0.9.0a} [Tech Reimagined] (techreimagined-1.9.4-1-univeral.jar) 
	UC	Tesla{1.1.0.24} [TESLA] (Tesla-1.9.4-1.1.0.24.jar) 
	UC	watchfulchevsky{b6} [Trust Is Nice, But...] (TINB_1.9_b6.jar) 
	UC	tis3d{0.9.0.5} [TIS-3D] (TIS-3D-MC1.9.4-0.9.0.5.jar) 
	UC	ICSE{1.0.0.0} [I Can See Everything] (Wawla-1.9.4-2.2.1.192.jar) 
	UC	wawla{2.2.1.188} [What Are We Looking At] (Wawla-1.9.4-2.2.1.192.jar) 
	UC	ZDoctorBB{1.1} [Blood Baubles] (ZDoctorBB-1.1.jar) 
	Loaded coremods (and transformers): 
CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
LoadingPlugin (Quark-beta-24.jar)
  vazkii.quark.base.asm.ClassTransformer
Reborn Core ASM (RebornCore-1.9.4-2.5.3.44-universal.jar)
  reborncore.asm.RebornClassTransformer
LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  lumien.randomthings.asm.ClassTransformer
IC2core (industrialcraft-2-2.5.17-ex19.jar)
  
FMLPlugin (InventoryTweaks-1.61-dev-53.jar)
  invtweaks.forge.asm.ContainerTransformer
TransformerLoader (OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar)
  li.cil.oc.common.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.9.4-0.4.0.24-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)`

**Comment by TheCodedOne** [comment]
I'm not entirely sure what is causing this crash, I'll have a look into it.

**Comment by XileForce** [comment]
Yea wish I could provide more info :( the error seemed awfully generic.

**Comment by TheCodedOne** [comment]
i wouldn't recommend playing with tech reimagined currently.. there arent alot of features yet but more are coming in today's update

**Comment by XileForce** [comment]
Awesome! Was looking for some good tech mods. Thought I'd try some of the Tesla based ones. Ive got the one that adds solar panels but no machines lol. will definitely check out the update.

**Comment by TheCodedOne** [comment]
Yeah, im assuming you're talking about Darkhax's solarvillage, its more of an example of how to use the TeslaAPI

**Comment by TheCodedOne** [comment]
The update today should add more machines, actual power generation and energy conduits... if all goes to plan

**Comment by XileForce** [comment]
Yep thought it might pair well with this. I have tech reborn though so I think I can use Tesla power with that mod in the meantime. Sounds like an awesome update. 1.9.4 could use a good tech mod. I like the concept of yours.

**Comment by TheCodedOne** [comment]
Yeah, techreborn is tesla compatible but you have to enable it in the config, and Thanks!

**Comment by XileForce** [comment]
Well good luck on the update. I won't waste any more of your time haha. Let me know if you need any more info on the crash. Will do what I can to help.

**Comment by TheCodedOne** [comment]
This has now been fixed and an update will be out soon.
